# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'InstagramClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstagramClone
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Firebase/Messaging'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'ActiveLabel'
	pod 'SDWebImage', '~> 5.0'
	pod 'JGProgressHUD'
	pod 'YPImagePicker'

  target 'InstagramCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstagramCloneUITests' do
    # Pods for testing
  end

end
