# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'InstagramClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstagramClone
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'Firebase/Messaging'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'ActiveLabel'
	pod 'SDWebImage', '~> 5.0'
	pod 'JGProgressHUD'
	pod 'YPImagePicker'
	use_frameworks!

  target 'InstagramCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstagramCloneUITests' do
    # Pods for testing
  end

post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
          end
      end
  end

end
